name: push-to-ecr

on: 
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    environment: Workflow
    steps:
      - name: Checkout # UNDERSTOOD
        uses: actions/checkout@v3

      - name: Set up Docker Buildx # UNDERSTOOD
        uses: docker/setup-buildx-action@v2
      
      - name: Set up QEMU # PARTICALLY UNDERSTOOD
        uses: docker/setup-qemu-action@v3

      - name: Configure AWS credentials # UNDERSTOOD
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR # UNDERSTOOD
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set short sha # UNDERSTOOD
        id: sha_short
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build and push # UNDERSTOOD
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ vars.ECR_REPOSITORY }}:${{ steps.sha_short.outputs.sha_short }} #UNDERSTOOD
          cache-from: type=local,src=/tmp/.buildx-cache # PARTICALLY UNDERSTOOD
          cache-to: type=local,dest=/tmp/.buildx-cache
          provenance: false
